### ISSUE TITLE
Issue with Node 6.0.X

### ISSUE THREAD

**Issue by gs-akhan** [wesbos/Learn-Redux#2]
```
Module build failed: TypeError: /Users/noob/Learn-Redux/client/styles/style.styl:146:1
   142|     border-width: 0 size size 0
   143|     border-color: transparent blue transparent transparent
   144|     top 30%
   145|     left 0
   146| 
--------^
   147| 
   148| 
   149| 

Path must be a string. Received undefined
```
As when I do npm start I get this error, suspecting this is a issue with webpack 

Thanks

**Comment by rublev** [comment]
Upgrade the `stylus-loader` package to `2.1.0` and install `stylus`. Then run npm start again, it will compile.

    "stylus": "^0.54.5",
    "stylus-loader": "^2.1.0",

**Comment by gs-akhan** [comment]
Let me give it a try 
Thanks

**Comment by wesbos** [comment]
Did that work?

**Comment by DrJid** [comment]
Had the same issue. Running node `6.2.0`. Updated stylus and yes it worked for me.

**Comment by rublev** [comment]
Thanks for confirming

**Comment by gs-akhan** [comment]
Yes. Worked.  Thanks

**Comment by Tiendq** [comment]
I believe that it needs to be put in the README file :)
