### ISSUE TITLE
why no containers?

### ISSUE THREAD

**Issue by roberto68** [wesbos/Learn-Redux#3]
well not an issue itself, but best way to to learn react, redux is to use containers - so you know exactly for given component what props, actions are mapped to what props, it's cleaner. Or I with play arouind with it during the weekend and make a pull request, is that OK?

**Comment by wesbos** [comment]
I chose to go simple on this and really drive home the ideas behind redux. 

I'd love to see how you do it, but I can't change the code for this repo as they correspond with the videos.
